const DIRECCIONES_CLINICAS = {
  CLINICA_SAN_RAFAEL_ZONA_12: "DIR-001",
  HOSPITAL_METROPOLITANO_ZONA_9: "DIR-002",
  CENTRO_MEDICO_LAS_CHARCAS_ZONA_11: "DIR-003",
  CLINICA_ESPECIALIZADA_MIXCO: "DIR-004",
  HOSPITAL_DEL_SUR_VILLA_NUEVA: "DIR-005",
  CLINICA_FAMILIAR_SAN_CRISTOBAL: "DIR-006",
  CENTRO_SALUD_ZONA_1: "DIR-007",
  CLINICA_SANTA_LUCIA_SAN_MIGUEL_PETAPA: "DIR-008",
  HOSPITAL_PRIVADO_EL_FRANCES: "DIR-009",
  CLINICA_MEDICA_LOS_PROCERES: "DIR-010",
  CENTRO_MEDICO_SAN_JOSE_ZONA_2: "DIR-011",
  CLINICA_ESPECIALIDADES_ZONA_10: "DIR-012",
  HOSPITAL_REGIONAL_ESCUINTLA: "DIR-013",
  CLINICA_SAN_JUAN_CHIMALTENANGO: "DIR-014",
  CENTRO_MEDICO_QUETZALTENANGO: "DIR-015",
};

module.exports = { DIRECCIONES_CLINICAS };
