const ESPECIALIDADES = {
  MEDICINA_GENERAL: "ESP-001",
  PEDIATRIA: "ESP-002",
  CARDIOLOGIA: "ESP-003",
  GINECOLOGIA: "ESP-004",
  NEUROLOGIA: "ESP-005",
  DERMATOLOGIA: "ESP-006",
  ORTOPEDIA: "ESP-007",
  OTORRINOLARINGOLOGIA: "ESP-008",
  PSICOLOGIA_CLINICA: "ESP-009",
  OTRA: "ESP-010",
};

module.exports = { ESPECIALIDADES };
