const EVENTOS = {
  CITA_AGENDADA: "EVT-001",
  CITA_CONFIRMADA: "EVT-002",
  CITA_COMPLETADA: "EVT-003",
  CITA_CANCELADA_PAC: "EVT-004",
  CITA_CANCELADA_MED: "EVT-005",
  CITA_REPROGRAMADA: "EVT-006",
  CITA_NO_ASISTIDA: "EVT-007",
  RECETA_EMITIDA: "EVT-008",
  DIAGNOSTICO_REG: "EVT-009",
};

module.exports = { EVENTOS };
